spring.application.name=navvirtual-backend
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5433/navvirtual
spring.datasource.username=navvirtual_user
spring.datasource.password=navvirtual_pass
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alec64670@gmail.com
spring.mail.password=zodnjlhxeohqfyva
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
jwt.secret=fLp7qxnkCCDCtihpwQgO0wTAe/1ZX69fDKGQwUhPX7I=
jwt.expiration=86400000
mercadopago.access-token=APP_USR-4846593513644537-073019-dddee57824dc636c2f125bbf539050f6-3580645010
mercadopago.public-key=APP_USR-e6a3b3c4-4114-40ae-bc46-f60406588189